/**
 * Pre-session onboarding contract for the tutor agent.
 *
 * The Studyus tutor grounds every turn on real curriculum evidence (transcribed
 * PDF pages) and the learner's own onboarding answers. There are no scripted
 * placeholder subjects — "Orbital Mechanics" and the canned per-subject
 * greet/explain/practice/quiz scripts were removed so the board never shows
 * fabricated content on first entry. Instead, after a curriculum subsection is
 * fetched and transcribed, the agent asks a fixed set of onboarding questions;
 * the answers become a consistent system reminder threaded into every tutor
 * turn via `buildOnboardingReminder` (see `src/lib/tutor.ts`).
 */

export type Intent = "greet" | "explain" | "practice" | "quiz";

/** Minimal Subject type for backward compat with SessionCard/SubjectIcon. */
export interface Subject {
  id: string;
  label: string;
  topic: string;
  icon: "orbit" | "sigma" | "binary" | "landmark";
}

/** Stub SCRIPTS — SessionCard imports it but it's unused. */
export const SCRIPTS: Record<string, any> = {};

/** Stub shape — SessionCard imports it but it's unused. */
export function shape(_intent: Intent, _subject: Subject): string {
  return "";
}

/**
 * The onboarding interview is generated by the tutor agent at session start —
 * see `generateOnboardingQuestions` in `src/lib/tutor.ts`. The questions are
 * written fresh for the specific concept (and its transcribed curriculum
 * evidence), so nothing here is a fixed question list.
 *
 * The interview reaches the learner through the agent's `create_forms` tool
 * call: instead of a numbered chat message, the counsellor posts its own short
 * note and a form card appears in the chat; the learner opens the card to
 * answer in a floating sheet with a mix of free-text, multiple-choice and
 * conditionally-gated questions. The chat input is locked while the form is
 * unanswered — the form IS the only answer path.
 *
 * This module owns only the *shape* of the interview and how the answers are
 * folded back into the tutor's system prompt.
 */

/** The one tool the onboarding flow exposes to the counsellor agent. */
export const CREATE_FORMS_TOOL = "create_forms";

/** Answer format the counsellor picks per question in its create_forms call. */
export type OnboardingQuestionKind = "free" | "choice";

/** One question the tutor agent generated for this session's concept. */
export interface OnboardingQuestion {
  /** Stable id within the interview, used to pair answers back to questions. */
  id: string;
  /** The question text as the learner sees it. */
  question: string;
  /** Free-text line or multiple choice. Missing on pre-form payloads — those
   *  interviews were always answered in writing, so absence means "free". */
  kind?: OnboardingQuestionKind;
  /** Two to six options when kind is "choice"; absent on "free" questions. */
  options?: string[];
  /** Ask this question only when an earlier question landed on one of these
   *  answers. Constraints keep the intake honest: probing which part feels
   *  shakiest is meaningless for a learner who has never met the concept at
   *  all, so such a probe is gated on the footing question's other options.
   *  Hidden questions submit as skipped. */
  onlyIf?: { questionId: string; anyOf: string[] };
}

/**
 * The questions visible under a partial draft: a gated question appears once
 * its earlier choice question's selected option matches `anyOf`
 * (case-insensitive). Questions gated on an unanswered question stay hidden —
 * the intake must not presume an answer it does not have.
 */
export function visibleOnboardingQuestions(
  questions: OnboardingQuestion[],
  answers: Record<string, string>
): OnboardingQuestion[] {
  return questions.filter((q) => {
    const gate = q.onlyIf;
    if (!gate) return true;
    const picked = (answers[gate.questionId] ?? "").trim().toLowerCase();
    if (!picked) return false;
    return gate.anyOf.some((option) => option.trim().toLowerCase() === picked);
  });
}

/** The artifact produced by the agent's `create_forms` tool call. */
export interface OnboardingForm {
  /** Short agent-written title for the chat card and the form sheet header. */
  title?: string;
  /** The agent's own invitation sentence, shown inside the form. */
  invitation?: string;
  questions: OnboardingQuestion[];
}

/** One answered question. `answer` is empty when the learner skipped it. */
export interface OnboardingAnswer {
  question: string;
  answer: string;
}

export interface OnboardingAnswers {
  /** The concept the interview was generated for. */
  concept: string;
  answers: OnboardingAnswer[];
}

/**
 * Render the learner's form submission as their chat reply, so the transcript
 * stays readable and the copy flow keeps working. Only the numbering and the
 * "(skipped)" marker come from the app — the words themselves are the
 * learner's.
 */
export function renderOnboardingReply(answers: OnboardingAnswers): string {
  return answers.answers
    .map((entry, i) => `${i + 1}. ${entry.answer || "(skipped)"}`)
    .join("\n");
}

/**
 * Compose the answers into a consistent system reminder appended to the tutor
 * agent's system prompt for the whole session, so the agent tutors to the
 * learner's stated situation across every turn rather than forgetting it after
 * the opener.
 */
export function buildOnboardingReminder(answers: OnboardingAnswers): string {
  const lines = answers.answers.map(
    (a) => `- ${a.question}\n  → ${a.answer || "not given"}`
  );
  return [
    `LEARNER ONBOARDING for "${answers.concept}" (consistent reminder for this session):`,
    ...lines,
    "Tutor to these answers for the duration of the session.",
    "If these answers say the learner is new to the concept — or they were all skipped — slow right down: introduce one idea at a time, define every technical term in plain language before you use it (never open a sentence on jargon the learner has not defined first), and check understanding before stacking vocabulary on vocabulary.",
  ].join("\n");
}
