/**
 * Pre-session onboarding contract for the tutor agent.
 *
 * The Studyus tutor grounds every turn on real curriculum evidence (transcribed
 * PDF pages) and the learner's own onboarding answers. There are no scripted
 * placeholder subjects — "Orbital Mechanics" and the canned per-subject
 * greet/explain/practice/quiz scripts were removed so the board never shows
 * fabricated content on first entry. Instead, after a curriculum subsection is
 * fetched and transcribed, the agent asks a fixed set of onboarding questions;
 * the answers become a consistent system reminder threaded into every tutor
 * turn via `buildOnboardingReminder` (see `src/lib/tutor.ts`).
 */

import type { SelfReportedFamiliarity } from "../lib/learning/types";

export type Intent = "greet" | "explain" | "practice" | "quiz";

/** Minimal Subject type for backward compat with SessionCard/SubjectIcon. */
export interface Subject {
  id: string;
  label: string;
  topic: string;
  icon: "orbit" | "sigma" | "binary" | "landmark";
}

/** Stub SCRIPTS — SessionCard imports it but it's unused. */
export const SCRIPTS: Record<string, any> = {};

/** Stub shape — SessionCard imports it but it's unused. */
export function shape(_intent: Intent, _subject: Subject): string {
  return "";
}

/**
 * The onboarding interview is generated by the tutor agent at session start —
 * see `generateOnboardingQuestions` in `src/lib/tutor.ts`. The questions are
 * written fresh for the specific concept (and its transcribed curriculum
 * evidence), so nothing here is a fixed question list.
 *
 * The interview reaches the learner through the agent's `create_forms` tool
 * call: instead of a numbered chat message, the counsellor posts its own short
 * note and a form card appears in the chat; the learner opens the card to
 * answer in a floating sheet with a mix of free-text, multiple-choice and
 * conditionally-gated questions. The chat input is locked while the form is
 * unanswered — the form IS the only answer path.
 *
 * This module owns only the *shape* of the interview and how the answers are
 * folded back into the tutor's system prompt.
 */

/** The one tool the onboarding flow exposes to the counsellor agent. */
export const CREATE_FORMS_TOOL = "create_forms";

/** Answer format the counsellor picks per question in its create_forms call. */
export type OnboardingQuestionKind = "free" | "choice";

/** One answer label's deterministic policy meaning on the footing question. */
export interface OnboardingFamiliarityOption {
  option: string;
  familiarity: SelfReportedFamiliarity;
}

/** One question the tutor agent generated for this session's concept. */
export interface OnboardingQuestion {
  /** Stable id within the interview, used to pair answers back to questions. */
  id: string;
  /** The question text as the learner sees it. */
  question: string;
  /** Free-text line or multiple choice. Missing on pre-form payloads — those
   *  interviews were always answered in writing, so absence means "free". */
  kind?: OnboardingQuestionKind;
  /** Two to six options when kind is "choice"; absent on "free" questions. */
  options?: string[];
  /** Exactly one footing question maps each visible option to a canonical,
   *  non-evidence entry-routing signal. */
  familiarityOptions?: OnboardingFamiliarityOption[];
  /** Ask this question only when an earlier question landed on one of these
   *  answers. Constraints keep the intake honest: probing which part feels
   *  shakiest is meaningless for a learner who has never met the concept at
   *  all, so such a probe is gated on the footing question's other options.
   *  Hidden questions submit as skipped. */
  onlyIf?: { questionId: string; anyOf: string[] };
}

/**
 * The questions visible under a partial draft: a gated question appears once
 * its earlier choice question's selected option matches `anyOf`
 * (case-insensitive). Questions gated on an unanswered question stay hidden —
 * the intake must not presume an answer it does not have.
 */
export function visibleOnboardingQuestions(
  questions: OnboardingQuestion[],
  answers: Record<string, string>
): OnboardingQuestion[] {
  return questions.filter((q) => {
    const gate = q.onlyIf;
    if (!gate) return true;
    const picked = (answers[gate.questionId] ?? "").trim().toLowerCase();
    if (!picked) return false;
    return gate.anyOf.some((option) => option.trim().toLowerCase() === picked);
  });
}

/** The artifact produced by the agent's `create_forms` tool call. */
export interface OnboardingForm {
  /** Short agent-written title for the chat card and the form sheet header. */
  title?: string;
  /** The agent's own invitation sentence, shown inside the form. */
  invitation?: string;
  questions: OnboardingQuestion[];
}

/** One answered question. `answer` is empty when the learner skipped it. */
export interface OnboardingAnswer {
  question: string;
  answer: string;
}

export interface OnboardingAnswers {
  /** The concept the interview was generated for. */
  concept: string;
  answers: OnboardingAnswer[];
  /** Learner-declared footing derived only from the validated choice mapping.
   *  It informs the first empty Encounter route; it is not mastery evidence. */
  selfReportedFamiliarity?: SelfReportedFamiliarity;
}

/** Derive the policy-only footing signal without interpreting free text. */
export function deriveSelfReportedFamiliarity(
  form: OnboardingForm,
  answers: Record<string, string>
): SelfReportedFamiliarity | undefined {
  const footing = form.questions.find((question) => question.familiarityOptions?.length);
  if (!footing) return undefined;
  const selected = (answers[footing.id] ?? "").trim().toLowerCase();
  return footing.familiarityOptions?.find(
    ({ option }) => option.trim().toLowerCase() === selected
  )?.familiarity;
}

/**
 * Render the learner's form submission as their chat reply, so the transcript
 * stays readable and the copy flow keeps working. Only the numbering and the
 * "(skipped)" marker come from the app — the words themselves are the
 * learner's.
 */
export function renderOnboardingReply(answers: OnboardingAnswers): string {
  return answers.answers
    .map((entry, i) => `${i + 1}. ${entry.answer || "(skipped)"}`)
    .join("\n");
}

/**
 * Compose the answers into a consistent system reminder appended to the tutor
 * agent's system prompt for the whole session, so the agent tutors to the
 * learner's stated situation across every turn rather than forgetting it after
 * the opener.
 *
 * Expanded to include: learning goal, misconceptions, time budget.
 */
export function buildOnboardingReminder(answers: OnboardingAnswers): string {
  // Parse answers into named fields for structured prompting
  const byQuestion = new Map(answers.answers.map((a) => [a.question.toLowerCase().slice(0, 40), a.answer]));

  const lines = answers.answers.map(
    (a) => `- ${a.question}\n  → ${a.answer || "not given"}`
  );

  // Extract the goal if present (heuristic: longest free-text answer)
  const goalAnswer = answers.answers.find((a) =>
    a.answer.length > 20 && a.question.toLowerCase().includes("end") || a.question.toLowerCase().includes("able")
  );

  // Extract misconceptions if present
  const misconceptionAnswer = answers.answers.find((a) =>
    a.question.toLowerCase().includes("confus") || a.question.toLowerCase().includes("mistake")
  );

  const sections: string[] = [
    `LEARNER ONBOARDING for "${answers.concept}" (consistent reminder for this session):`,
    ...lines,
  ];

  if (goalAnswer?.answer) {
    sections.push("", `SESSION GOAL: "${goalAnswer.answer}" — teach toward this observable outcome.`);
  }

  if (misconceptionAnswer?.answer) {
    sections.push("", `KNOWN MISCONCEPTIONS to address: "${misconceptionAnswer.answer}"`);
  }

  sections.push(
    "",
    "Tutor to these answers for the duration of the session.",
    "If these answers say the learner is new to the concept — or they were all skipped — slow right down: introduce one idea at a time, define every technical term in plain language before you use it (never open a sentence on jargon the learner has not defined first), and check understanding before stacking vocabulary on vocabulary.",
    "If a learning goal is stated, work backward from it: every teaching move must serve that outcome.",
    "If misconceptions are stated, address them proactively — do not wait for them to surface on a wrong answer."
  );

  return sections.join("\n");
}
