/**
 * Pre-session onboarding contract for the tutor agent.
 *
 * The Studyus tutor grounds every turn on real curriculum evidence (transcribed
 * PDF pages) and the learner's own onboarding answers. There are no scripted
 * placeholder subjects — "Orbital Mechanics" and the canned per-subject
 * greet/explain/practice/quiz scripts were removed so the board never shows
 * fabricated content on first entry. Instead, after a curriculum subsection is
 * fetched and transcribed, the agent asks a fixed set of onboarding questions;
 * the answers become a consistent system reminder threaded into every tutor
 * turn via `buildOnboardingReminder` (see `src/lib/tutor.ts`).
 */

export type Intent = "greet" | "explain" | "practice" | "quiz";

/** Minimal Subject type for backward compat with SessionCard/SubjectIcon. */
export interface Subject {
  id: string;
  label: string;
  topic: string;
  icon: "orbit" | "sigma" | "binary" | "landmark";
}

/** Stub SCRIPTS — SessionCard imports it but it's unused. */
export const SCRIPTS: Record<string, any> = {};

/** Stub shape — SessionCard imports it but it's unused. */
export function shape(_intent: Intent, _subject: Subject): string {
  return "";
}

/**
 * The onboarding interview is generated by the tutor agent at session start —
 * see `generateOnboardingQuestions` in `src/lib/tutor.ts`. The questions are
 * written fresh for the specific concept (and its transcribed curriculum
 * evidence), so nothing here is a fixed question list.
 *
 * The interview reaches the learner through the agent's `create_forms` tool
 * call: instead of a numbered chat message, the counsellor posts its own short
 * note and a form card appears in the chat; the form opens as a floating sheet
 * with a mix of free-text and multiple-choice questions. A learner who instead
 * types the answers into the chat input still works — `pairOnboardingReply`
 * covers that path.
 *
 * This module owns only the *shape* of the interview and how the answers are
 * folded back into the tutor's system prompt.
 */

/** The one tool the onboarding flow exposes to the counsellor agent. */
export const CREATE_FORMS_TOOL = "create_forms";

/** Answer format the counsellor picks per question in its create_forms call. */
export type OnboardingQuestionKind = "free" | "choice";

/** One question the tutor agent generated for this session's concept. */
export interface OnboardingQuestion {
  /** Stable id within the interview, used to pair answers back to questions. */
  id: string;
  /** The question text as the learner sees it. */
  question: string;
  /** Free-text line or multiple choice. Missing on pre-form payloads — those
   *  interviews were always answered in writing, so absence means "free". */
  kind?: OnboardingQuestionKind;
  /** Two to six options when kind is "choice"; absent on "free" questions. */
  options?: string[];
}

/** The artifact produced by the agent's `create_forms` tool call. */
export interface OnboardingForm {
  /** Short agent-written title for the chat card and the form sheet header. */
  title?: string;
  /** The agent's own invitation sentence, shown inside the form. */
  invitation?: string;
  questions: OnboardingQuestion[];
}

/** One answered question. `answer` is empty when the learner skipped it. */
export interface OnboardingAnswer {
  question: string;
  answer: string;
}

export interface OnboardingAnswers {
  /** The concept the interview was generated for. */
  concept: string;
  answers: OnboardingAnswer[];
}

/**
 * Render the learner's form submission as their chat reply, so the transcript
 * stays readable and the copy flow keeps working. Only the numbering and the
 * "(skipped)" marker come from the app — the words themselves are the
 * learner's.
 */
export function renderOnboardingReply(answers: OnboardingAnswers): string {
  return answers.answers
    .map((entry, i) => `${i + 1}. ${entry.answer || "(skipped)"}`)
    .join("\n");
}

/**
 * Pair a free-text reply back onto the generated questions. One line per
 * question, in order; numeric prefixes ("1.") are stripped. Missing or
 * skip-style lines become empty answers, which the reminder reports as
 * "not given" rather than inventing a value.
 */
export function pairOnboardingReply(
  concept: string,
  questions: OnboardingQuestion[],
  reply: string
): OnboardingAnswers {
  const lines = reply
    .split(/\r?\n/)
    .map((line) => line.replace(/^\s*\d+[.)]\s*/, "").trim())
    .filter((line) => line.length > 0);
  const isSkip = (s: string) => /^(skip|n\/a|na|none|-)$/i.test(s);
  return {
    concept,
    answers: questions.map((q, i) => {
      const raw = lines[i] ?? "";
      return { question: q.question, answer: isSkip(raw) ? "" : raw };
    }),
  };
}

/**
 * Compose the answers into a consistent system reminder appended to the tutor
 * agent's system prompt for the whole session, so the agent tutors to the
 * learner's stated situation across every turn rather than forgetting it after
 * the opener.
 */
export function buildOnboardingReminder(answers: OnboardingAnswers): string {
  const lines = answers.answers.map(
    (a) => `- ${a.question}\n  → ${a.answer || "not given"}`
  );
  return [
    `LEARNER ONBOARDING for "${answers.concept}" (consistent reminder for this session):`,
    ...lines,
    "Tutor to these answers for the duration of the session.",
  ].join("\n");
}
